# Workflow that builds the docker image for ARM and x86_64 and pushes to GitHub packages

name: build

on:
  push:

jobs:
  # buildx-arm64:
  #   runs-on: ubuntu-24.04-arm
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v4      
  #     -
  #       name: Login to GHCR
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner  }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     -
  #       name: Set up Docker Buildx
  #       id: buildx
  #       uses: docker/setup-buildx-action@v3
  #     -
  #       name: Build and push
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: .
  #         platforms: linux/arm64
  #         push: true
  #         tags: ghcr.io/${{ github.repository_owner }}/dutil:latest
  
  buildx-x64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4      
      -
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner  }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/dutil:latest
